# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timeline', '0002_timeline_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeline',
            old_name='comment',
            new_name='comment1',
        ),
        migrations.AddField(
            model_name='timeline',
            name='comment2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
