# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.Company')),
            ],
            options={
                'db_table': 'crm_company_model',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('licenseid', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_lead',
            },
        ),
        migrations.CreateModel(
            name='Lead_Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.Company')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.Lead')),
            ],
            options={
                'db_table': 'crm_lead_vehicle',
            },
        ),
        migrations.CreateModel(
            name='MakeYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makeyear', models.IntegerField()),
                ('model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CRM.Company_Model')),
            ],
            options={
                'db_table': 'crm_makeyear',
            },
        ),
        migrations.CreateModel(
            name='Qualify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=3)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.Lead')),
            ],
            options={
                'db_table': 'crm_qualify',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'crm_question',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'crm_status',
            },
        ),
        migrations.AddField(
            model_name='qualify',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.Question'),
        ),
        migrations.AddField(
            model_name='lead_vehicle',
            name='makeyear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.MakeYear'),
        ),
        migrations.AddField(
            model_name='lead_vehicle',
            name='model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CRM.Company_Model'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.Status'),
        ),
    ]
